/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package sigh;
import javax.swing.*;
public class App {

    public static void main(String[] args) {
        
        SwingUtilities.invokeLater(() -> {
            String studentNumber = JOptionPane.showInputDialog("Enter studentNumner:");
            String name = JOptionPane.showInputDialog("Enter Name: ");
            String surname = JOptionPane.showInputDialog("Enter Surname: ");
            String email = JOptionPane.showInputDialog("Enter Email: ");
            String phoneNumber = JOptionPane.showInputDialog("Enter Phone Number: ");
            int mark1 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 1:"));
            int mark2 = Integer.parseInt(JOptionPane.showInputDialog("Enter Mark 2:"));
            int assignmentMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Assignment Mark: "));
            int examMark = Integer.parseInt(JOptionPane.showInputDialog("Enter Exam Mark: "));
            
            boolean dpStatus = ((mark1 + mark2 + assignmentMark) /3)>= 40;
            
            double courseworkAverage = (mark1 + mark2 + assignmentMark) /3;
            double finalMark = (courseworkAverage * 0.4) + (examMark * 0.6);
            
            String result = "Failed";
             if (finalMark >= 0 && finalMark <= 49) {
            result = "Failed";
        } else if (finalMark >= 47 && finalMark <= 49) {
            result = "Sup";
        } else if (finalMark >= 50 && finalMark <= 74) {
            result = "Pass";
        } else {
            result = "Distinction";
        }
        String message = "Student Number: " + studentNumber + "\n"
                + "Name: " + name + "\n"
                + "Email: " + email + "\n"
                + "Phone Number: " + phoneNumber + "\n"
                + "Mark one: " + mark1 + "\n"
                + "Mark two: " + mark2 + "\n"
                + "Assignment mark: " + assignmentMark + "\n"
                + "DP Status: " + dpStatus + "\n"
                + "Final Mark: " + finalMark + "\n"
                + "Achieved: " + result + "\n";
            JOptionPane.showMessageDialog(null, message);
        });
                }
}
